aliases:
  - &git_checkout
    name: Checkout
    command: |
      mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      git clone --depth 1 -b $CIRCLE_BRANCH $CIRCLE_REPOSITORY_URL ./ && \
      git checkout $CIRCLE_SHA1
  - &containerize_push
    name: Containerize and Push
    command: |
      echo $DOCKER_PASSWORD > docker_passwd && \
      docker login -u $DOCKER_USERNAME --password-stdin < docker_passwd && rm docker_passwd && \
      docker build --build-arg SW_HOSTNAME=$HOSTNAME -t aeternas/batch-shortlinker:$CIRCLE_BRANCH . && \
      docker push aeternas/batch-shortlinker:$CIRCLE_BRANCH
  - &environment
    LEIN_ROOT: "true"
    JVM_OPTS: -Xmx3200m
  - &restore_cache
    keys:
      - v1-dependencies-{{ checksum "project.clj" }}
      - v1-dependencies-
  - &save_cache
    paths:
      - ~/.m2
    key: v1-dependencies-{{ checksum "project.clj" }}
  - &export_env
    name: Export envs
    command: |
      if [ $CIRCLE_BRANCH == "master" ]; then 
        echo 'export HOSTNAME="$PROD_HOSTNAME"' >> $BASH_ENV
      else 
        echo 'export HOSTNAME="$DEV_HOSTNAME"' >> $BASH_ENV
      fi
  - &run
    name: Warm Cache
    command: |
      java -jar batch-shortlinker-0.1.0-SNAPSHOT-standalone.jar
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.7.1
    working_directory: ~/repo
    environment: *environment
    steps:
      - run: *git_checkout
      - restore_cache: *restore_cache
      - run: lein deps
      - save_cache: *save_cache
      - run: lein test
      - run: lein uberjar 
      - run: *export_env
      - store_artifacts:
          path: target/uberjar/batch-shortlinker-0.1.0-SNAPSHOT-standalone.jar
      - setup_remote_docker:
          docker_layer_caching: true
      - deploy: *containerize_push
  run:
    docker:
      - image: aeternas/batch-shortlinker:$CIRCLE_BRANCH
    working_directory: /home/circleci/repo
    steps:
      - deploy: *run
workflows:
  version: 2.1
  build-run:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - development
